version: '3'

services:
  web:
    build:
      context: ./client
      target: runner
    env_file:
      - ./client/.env.local
    volumes:
      - ./client:/app
      - /app/node_modules
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    links:
      - api
  db:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 80:80
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    links:
      - db

volumes:
  data: