import './globals.css'
import Header from '~/components/molecules/header'
import List from '~/components/molecules/list'
import Link from 'next/link'
import ItemList from '~/components/atoms/itemList'
import { CREATE_COMPANY, LOGIN } from '~/constants/routes'
import { Roboto } from 'next/font/google'
import { type Params } from '~/interface/params'
import { defaultLocale } from '../middleware'

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'es' }]
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const navItems = [
  {
    name: 'Home',
    href: '/'
  },
  {
    name: 'Login',
    href: LOGIN
  },
  {
    name: 'Register',
    href: CREATE_COMPANY
  },
  {
    name: 'Add storage',
    href: '/logistic/addDeposit'
  }
]

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

interface RootLayoutProps extends Params {
  children: React.ReactNode
}

export default function RootLayout({ children, params: { lang } }: RootLayoutProps) {
  return (
    <html className={roboto.className} lang={lang ?? defaultLocale}>
      <body className="h-screen w-screen bg-[#FFFFFF] dark:bg-[#151515]">
        <Header title='Home'>
          <List>
            {navItems.map((item) => (
              <ItemList key={item.name}>
                <Link href={item.href}>
                  {item.name}
                </Link>
              </ItemList>
            ))}
          </List>
        </Header>
        {children}
      </body>
    </html>
  )
}
