import Header from '~/components/molecules/header'
import './globals.css'
import List from '~/components/molecules/list'
import Link from 'next/link'
import ItemList from '~/components/atoms/itemList'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const navItems = [
  {
    name: 'Home',
    href: '/'
  },
  {
    name: 'Login',
    href: '/common/auth/login'
  },
  {
    name: 'Register',
    href: '/common/auth/createCompany'
  }
]

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-screen h-screen'>
        <Header title='Home'>
          <List>
            {navItems.map((item) => (
              <ItemList key={item.name}>
                <Link href={item.href}>
                  {item.name}
                </Link>
              </ItemList>
            ))}
          </List>
        </Header>
        {children}
      </body>
    </html>
  )
}
