"""Fix 2

Revision ID: 2055ebc09239
Revises: ffdac788a883
Create Date: 2023-06-21 21:56:08.436473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2055ebc09239'
down_revision = 'ffdac788a883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_type_users_id', table_name='type_users')
    op.drop_table('type_users')
    op.drop_constraint('companys_users_id_fkey', 'companys', type_='foreignkey')
    op.drop_column('companys', 'users_id')
    op.drop_constraint('tipe_users_user_id_fkey', 'tipe_users', type_='foreignkey')
    op.drop_column('tipe_users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipe_users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tipe_users_user_id_fkey', 'tipe_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('companys', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('companys_users_id_fkey', 'companys', 'users', ['users_id'], ['id'], ondelete='SET NULL')
    op.create_table('type_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='type_users_pkey'),
    sa.UniqueConstraint('name', name='type_users_name_key')
    )
    op.create_index('ix_type_users_id', 'type_users', ['id'], unique=False)
    # ### end Alembic commands ###
