"""uuid 2

Revision ID: 2afa73f0f532
Revises: 566e14c8fe59
Create Date: 2023-07-09 14:48:59.213697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afa73f0f532'
down_revision = '566e14c8fe59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change user uuid to uuid type in postgresql
    op.alter_column('users', 'uuid', type_=sa.dialects.postgresql.UUID(as_uuid=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
