"""change type uuid

Revision ID: 2e092944e341
Revises: 2afa73f0f532
Create Date: 2023-07-12 14:11:14.483041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e092944e341'
down_revision = '2afa73f0f532'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'comment')
    # ### end Alembic commands ###
