"""Testing

Revision ID: 33c96dceaa44
Revises: fc1eeea4bd95
Create Date: 2023-06-21 21:43:31.681035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c96dceaa44'
down_revision = 'fc1eeea4bd95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companys', 'users', ['users_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('tipe_users_user_id_fkey', 'tipe_users', type_='foreignkey')
    op.create_foreign_key(None, 'tipe_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('type_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_company_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tipe_users', ['type_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'companys', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_company_id_fkey', 'users', 'companys', ['company_id'], ['id'])
    op.drop_column('users', 'type_user_id')
    op.drop_constraint(None, 'tipe_users', type_='foreignkey')
    op.create_foreign_key('tipe_users_user_id_fkey', 'tipe_users', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'companys', type_='foreignkey')
    op.drop_column('companys', 'users_id')
    # ### end Alembic commands ###
