"""secon migrate

Revision ID: 3ed75c70aa17
Revises: f97fbf73da6b
Create Date: 2023-06-16 20:47:49.683551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed75c70aa17'
down_revision = 'f97fbf73da6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
