"""uuid

Revision ID: 566e14c8fe59
Revises: 9dbf92c0ff05
Create Date: 2023-07-09 14:40:20.571186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566e14c8fe59'
down_revision = '9dbf92c0ff05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
