"""New tables

Revision ID: 5a9cc5933f99
Revises: a8e9d0d68478
Create Date: 2023-07-05 21:15:24.889369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9cc5933f99'
down_revision = 'a8e9d0d68478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
