"""New migration

Revision ID: 93eca691179b
Revises: 5a9cc5933f99
Create Date: 2023-07-06 19:23:28.352100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eca691179b'
down_revision = '5a9cc5933f99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
