"""Descripción de la revisión

Revision ID: 9dbf92c0ff05
Revises: 93eca691179b
Create Date: 2023-07-09 14:30:25.566987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbf92c0ff05'
down_revision = '93eca691179b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    op.drop_constraint('users_type_user_id_key', 'users', type_='unique')
    op.drop_constraint('users_uuid_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_unique_constraint('users_uuid_key', 'users', ['uuid'])
    op.create_unique_constraint('users_type_user_id_key', 'users', ['type_user_id'])
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
