"""Relation delete

Revision ID: a8e9d0d68478
Revises: 5780f39ab661
Create Date: 2023-07-05 21:09:40.290380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e9d0d68478'
down_revision = '5780f39ab661'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ## Drop all tables and relations
    op.drop_constraint('fk_company_user', 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')

    op.drop_constraint('fk_type_user_user', 'users', type_='foreignkey')
    op.drop_column('users', 'type_user_id')
    
    op.drop_constraint('fk_user_type_user', 'type_users', type_='foreignkey')
    op.drop_column('type_users', 'user_id')

    op.drop_constraint('fk_user_company', 'companys', type_='foreignkey')
    op.drop_column('companys', 'user_id')

    op.drop_table('type_users')
    op.drop_table('users')
    op.drop_table('companys')

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### end Alembic commands ###
