"""user private

Revision ID: ae6ef53b05b2
Revises: 0b185320d4f5
Create Date: 2023-07-05 19:49:54.896037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6ef53b05b2'
down_revision = '0b185320d4f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
