"""No realtions

Revision ID: d2dc3d4089f1
Revises: ae6ef53b05b2
Create Date: 2023-07-05 19:54:26.059567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dc3d4089f1'
down_revision = 'ae6ef53b05b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
