"""migrasao 2

Revision ID: fc1eeea4bd95
Revises: 6fade4d6ef24
Create Date: 2023-06-21 20:49:08.788065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1eeea4bd95'
down_revision = '6fade4d6ef24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipe_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tipe_users_id'), 'tipe_users', ['id'], unique=False)
    op.add_column('users', sa.Column('type_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tipe_users', ['type_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'type_user_id')
    op.drop_index(op.f('ix_tipe_users_id'), table_name='tipe_users')
    op.drop_table('tipe_users')
    # ### end Alembic commands ###
