import Header from '~/components/molecules/header'
import '../globals.css'
import List from '~/components/molecules/list'
import Link from 'next/link'
import ItemList from '~/components/atoms/itemList'
import { CREATE_COMPANY, LOGIN } from '~/constants/routes'
import { Roboto } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const navItems = [
  {
    name: 'Home',
    href: '/'
  },
  {
    name: 'Login',
    href: LOGIN
  },
  {
    name: 'Register',
    href: CREATE_COMPANY
  }
]
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html className={roboto.className} lang="en">
      <body className="h-screen w-screen bg-white dark:bg-black">
        <Header title='Home'>
          <List>
            {navItems.map((item) => (
              <ItemList key={item.name}>
                <Link href={item.href}>
                  {item.name}
                </Link>
              </ItemList>
            ))}
          </List>
        </Header>
        {children}
      </body>
    </html>
  )
}
