FROM python:3.8.10-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

COPY ./app /app

RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]