FROM python:3.8.10-slim

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

COPY ./app /api

RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]