FROM python:3.11

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

COPY ./app /app

RUN pip install --no-cache -r requirements.txt

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]